### Base URL
http://microbloglite.us-east-2.elasticbeanstalk.com

### Step 1) Register or create new user
POST http://microbloglite.us-east-2.elasticbeanstalk.com/api/users
Content-Type: application/json

{
    "username": "eort5",
    "fullName": "Erik",
    "password": "Erik435"
}



### Step 2) Login

POST http://microbloglite.us-east-2.elasticbeanstalk.com/auth/login
Content-Type: application/json

{
    "username": "eort5",
    "password": "Erik435"
}

# User Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVvcnQ1IiwiaWF0IjoxNzE4OTgzNTAwLCJleHAiOjE3MTkwNjk5MDB9.8ehsw1vO6y-02R6KcIpzK1COcszou3DCA9kGEncdFK8

### Step 3) GET Users

GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVvcnQ1IiwiaWF0IjoxNzE4OTgzNTAwLCJleHAiOjE3MTkwNjk5MDB9.8ehsw1vO6y-02R6KcIpzK1COcszou3DCA9kGEncdFK8


### Step 4) GET One User
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/users/eort5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVvcnQ1IiwiaWF0IjoxNzE4OTgzNTAwLCJleHAiOjE3MTkwNjk5MDB9.8ehsw1vO6y-02R6KcIpzK1COcszou3DCA9kGEncdFK8

### Step 5) Create a Post
POST http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVvcnQ1IiwiaWF0IjoxNzE4OTgzNTAwLCJleHAiOjE3MTkwNjk5MDB9.8ehsw1vO6y-02R6KcIpzK1COcszou3DCA9kGEncdFK8
Content-Type: application/json

{
    "text": "Testing Testing testing..."
}


### Step 6) GET Posts
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVvcnQ1IiwiaWF0IjoxNzE4OTgzNTAwLCJleHAiOjE3MTkwNjk5MDB9.8ehsw1vO6y-02R6KcIpzK1COcszou3DCA9kGEncdFK8

### Step 7) DELETE Post
DELETE http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts/6675a075fbf13c2cc0eaf6d9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVvcnQ1IiwiaWF0IjoxNzE4OTgzNTAwLCJleHAiOjE3MTkwNjk5MDB9.8ehsw1vO6y-02R6KcIpzK1COcszou3DCA9kGEncdFK8

### Step 8) Update User
PUT http://microbloglite.us-east-2.elasticbeanstalk.com/api/users/eort5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVvcnQ1IiwiaWF0IjoxNzE4OTgzNTAwLCJleHAiOjE3MTkwNjk5MDB9.8ehsw1vO6y-02R6KcIpzK1COcszou3DCA9kGEncdFK8
Content-Type: application/json

{
    "password": "erick435",
    "bio": "Coding...",
    "fullName": "Erik O"
}

### Step 9) Add Like
POST http://microbloglite.us-east-2.elasticbeanstalk.com/api/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVvcnQ1IiwiaWF0IjoxNzE4OTgzNTAwLCJleHAiOjE3MTkwNjk5MDB9.8ehsw1vO6y-02R6KcIpzK1COcszou3DCA9kGEncdFK8
Content-Type: application/json

{
    "postId": "I liked this post"
}


### Step 10) Delete/Remove Like
DELETE http://microbloglite.us-east-2.elasticbeanstalk.com/api/likes/6675a3ebfbf13c2cc0eaf78f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVvcnQ1IiwiaWF0IjoxNzE4OTgzNTAwLCJleHAiOjE3MTkwNjk5MDB9.8ehsw1vO6y-02R6KcIpzK1COcszou3DCA9kGEncdFK8
